version: "3.2"

services:
  # App
  server:
    container_name: app
    build: .
    env_file: .env
    restart: always
    ports:
      - 50000:5000
    volumes:
      - './upload_dir:/server/upload_dir'
      - './android_includes:/server/android_includes'
    depends_on:
      - database
    links:
      - database
    networks:
      - local-net

  # MariaDB
  database:
    container_name: database
    image: mariadb:bionic
    env_file: .env
    restart: always
    ports:
     - 3306:3306
    volumes:
     - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - local-net

networks:
  local-net:
    driver: bridge