name: SonarQube


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  sonar-sanner:
    name: sonar-sanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SonarQube Scanner
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
